(() => {
  const categories={preparation:['準備風景','PREPARATION','目高祭に向けた準備の様子です。'],creation:['制作の手元','MAKING','装飾や作品づくりの手元を集めました。'],'after-school':['放課後','AFTER SCHOOL','放課後に進む準備の様子です。'],rehearsal:['リハーサル','REHEARSAL','本番に向けた練習や確認の様子です。'],'final-prep':['開催直前','FINAL PREP','開催直前の仕上げの様子です。'],'festival-day':['目高祭当日','FESTIVAL DAYS','学年・部活動・その他・中夜祭のフォルダから、当日の様子をご覧ください。'],awards:['表彰・振り返り','AFTER THE FESTIVAL','努力が実を結ぶ瞬間と、目高祭を終えたあとの言葉。']};
  const groups={grade1:'1学年',grade2:'2学年',grade3:'3学年',club:'部活動',other:'その他',chuyasai:'中夜祭'};
  const params=new URLSearchParams(location.search),requested=params.get('category'),category=categories[requested]?requested:'preparation'; let group=null;
  if(category==='festival-day'&&groups[params.get('group')])group=params.get('group');
  if(requested!==category||(category==='festival-day'&&params.has('group')&&!group)){const next=new URL(location.href);next.searchParams.set('category',category);if(!group)next.searchParams.delete('group');history.replaceState(null,'',next)}
  const [title,kicker,description]=categories[category],groupLabel=group?groups[group]:'';
  document.title=`${title}${groupLabel?`｜${groupLabel}`:''}｜第79回 目高祭`; document.getElementById('gallery-title').textContent=groupLabel||title; document.getElementById('gallery-kicker').textContent=group?`${kicker} / ${title}`:kicker; document.getElementById('gallery-description').textContent=group?`${groupLabel}の写真を掲載しています。`:description;
  const folderNav=document.getElementById('festival-folder-nav'); if(category==='festival-day'&&group&&folderNav){folderNav.hidden=false;const back=document.createElement('a');back.href='gallery.html?category=festival-day';back.className='festival-folder-back';back.innerHTML='<strong>← フォルダ一覧へ</strong><small>目高祭当日</small>';folderNav.appendChild(back)}
  const grid=document.getElementById('gallery-grid'),state=document.getElementById('gallery-state'),total=document.getElementById('gallery-total'),lightbox=document.getElementById('gallery-lightbox'),lightboxImage=document.getElementById('lightbox-image'),lightboxCaption=document.getElementById('lightbox-caption'),lightboxCounter=document.getElementById('lightbox-counter'),closeBtn=lightbox.querySelector('.lightbox-close'),prevBtn=lightbox.querySelector('.lightbox-prev'),nextBtn=lightbox.querySelector('.lightbox-next');let photos=[],current=0,pointerStart=null;const cfg=window.MEKOUSAI_CONFIG||{},apiBase=String(cfg.apiBase||'').replace(/\/$/,''),configured=apiBase&&!apiBase.includes('REPLACE-WITH-WORKER');
  const fmtDate=value=>{if(!value)return'';const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return m?`${Number(m[2])}月${Number(m[3])}日`:value};
  function renderFolders(folders){grid.textContent='';grid.className='festival-folder-cards';state.hidden=true;total.textContent=`${folders.reduce((n,f)=>n+Number(f.count||0),0)} PHOTOS`;folders.forEach(folder=>{const a=document.createElement('a');a.className='festival-folder-card';a.href=`gallery.html?category=festival-day&group=${encodeURIComponent(folder.group)}`;const visual=document.createElement('div');visual.className='festival-folder-thumb';if(folder.coverUrl){const img=document.createElement('img');img.src=folder.coverUrl;img.alt=`${groups[folder.group]}の代表写真`;img.loading='lazy';visual.appendChild(img)}else{const empty=document.createElement('div');empty.className='festival-folder-empty';empty.textContent='PHOTO';visual.appendChild(empty)}const body=document.createElement('div');body.className='festival-folder-card-body';const label=document.createElement('div');label.className='festival-folder-label';const h2=document.createElement('h2');h2.textContent=groups[folder.group];const count=document.createElement('span');count.textContent=`${folder.count||0} PHOTOS`;const arrow=document.createElement('b');arrow.textContent='写真を見る';label.append(h2,count);body.append(label,arrow);a.append(visual,body);grid.appendChild(a)})}
  function render(){grid.className='gallery-grid';grid.textContent='';state.hidden=photos.length>0;if(!photos.length){state.textContent=group?`${groupLabel}の写真はまだありません。`:'まだ写真はありません。';total.textContent=group?`${groupLabel}｜0 PHOTOS`:'0 PHOTOS';return}total.textContent=group?`${groupLabel}｜${photos.length} PHOTOS`:`${photos.length} PHOTOS`;photos.forEach((photo,index)=>{const figure=document.createElement('figure');figure.className='gallery-card';const openButton=document.createElement('button');openButton.type='button';openButton.setAttribute('aria-label',`${index+1}枚目の写真を拡大`);const img=document.createElement('img');img.src=photo.url;img.alt=photo.caption||`${title}の写真 ${index+1}`;img.loading=index<4?'eager':'lazy';img.decoding='async';openButton.appendChild(img);openButton.addEventListener('click',()=>open(index));figure.appendChild(openButton);const caption=document.createElement('figcaption');if(photo.takenOn){const time=document.createElement('time');time.dateTime=photo.takenOn;time.textContent=fmtDate(photo.takenOn);caption.appendChild(time)}if(photo.caption){const p=document.createElement('p');p.textContent=photo.caption;caption.appendChild(p)}figure.appendChild(caption);grid.appendChild(figure)})}
  function showCurrent(){const photo=photos[current];if(!photo)return;lightboxImage.src=photo.url;lightboxImage.alt=photo.caption||`${title}の写真 ${current+1}`;lightboxCaption.textContent=[fmtDate(photo.takenOn),photo.caption].filter(Boolean).join('｜');lightboxCounter.textContent=`${current+1} / ${photos.length}`}
  function open(index){current=index;showCurrent();lightbox.hidden=false;document.body.style.overflow='hidden';closeBtn.focus()}function close(){lightbox.hidden=true;document.body.style.overflow='';lightboxImage.removeAttribute('src')}function move(step){if(!photos.length)return;current=(current+step+photos.length)%photos.length;showCurrent()}
  closeBtn.addEventListener('click',close);prevBtn.addEventListener('click',()=>move(-1));nextBtn.addEventListener('click',()=>move(1));lightbox.addEventListener('click',e=>{if(e.target===lightbox)close()});document.addEventListener('keydown',e=>{if(lightbox.hidden)return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});lightbox.addEventListener('pointerdown',e=>pointerStart=e.clientX);lightbox.addEventListener('pointerup',e=>{if(pointerStart===null)return;const delta=e.clientX-pointerStart;pointerStart=null;if(Math.abs(delta)>55)move(delta>0?-1:1)});
  if(!configured){state.textContent='写真公開システムの接続準備中です。';total.textContent='準備中';return}if(category==='festival-day'&&!group){fetch(`${apiBase}/api/festival-folders`,{headers:{Accept:'application/json'}}).then(res=>{if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json()}).then(payload=>renderFolders(Array.isArray(payload.folders)?payload.folders:[])).catch(()=>{state.hidden=false;state.className='gallery-error';state.textContent='フォルダの読み込みに失敗しました。少し時間をおいて再読み込みしてください。';total.textContent='読み込みエラー'});return}let endpoint=`${apiBase}/api/photos?category=${encodeURIComponent(category)}`;if(group)endpoint+=`&group=${encodeURIComponent(group)}`;fetch(endpoint,{headers:{Accept:'application/json'}}).then(res=>{if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.json()}).then(payload=>{photos=Array.isArray(payload.photos)?payload.photos:[];render()}).catch(()=>{state.hidden=false;state.className='gallery-error';state.textContent='写真の読み込みに失敗しました。少し時間をおいて再読み込みしてください。';total.textContent='読み込みエラー'})
})();